# Generated by Django 2.0.4 on 2018-04-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyPointer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_logo', to='companyPointer.LogoUpload'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(to='companyPointer.Tag'),
        ),
    ]
