# Generated by Django 2.0.4 on 2018-04-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyPointer', '0002_auto_20180412_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_logo', to='companyPointer.LogoUpload'),
        ),
    ]
