# Generated by Django 2.0.4 on 2018-04-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyPointer', '0003_auto_20180412_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_logo', to='companyPointer.LogoUpload'),
        ),
    ]
