# Generated by Django 2.0.4 on 2018-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyPointer', '0004_auto_20180413_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pos_lat',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='pos_lon',
            field=models.FloatField(default=10.0),
        ),
    ]
