# Generated by Django 2.0.4 on 2018-04-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyPointer', '0005_auto_20180413_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(choices=[(1, 'market'), (2, 'bank'), (3, 'cinema')], on_delete=django.db.models.deletion.CASCADE, related_name='company_type', to='companyPointer.CompanyType'),
        ),
    ]
