# Generated by Django 2.0.4 on 2018-04-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyPointer', '0006_auto_20180413_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_type', to='companyPointer.CompanyType'),
        ),
    ]
