# Generated by Django 2.0.4 on 2018-04-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyPointer', '0007_auto_20180413_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(related_name='company_tags', to='companyPointer.Tag'),
        ),
    ]
