# Generated by Django 2.0.4 on 2018-04-26 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(blank=True, default=None, null=True)),
                ('member_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_a', to=settings.AUTH_USER_MODEL)),
                ('member_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_b', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(related_name='chat_messages', to='chat.Message')),
            ],
        ),
    ]
