# Generated by Django 2.0.4 on 2018-04-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='chat_messages', to='chat.Message'),
        ),
    ]
