# Generated by Django 2.0.4 on 2018-04-15 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyPointer', '0008_auto_20180413_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_latitude', models.FloatField()),
                ('last_longitude', models.FloatField()),
                ('favourites', models.ManyToManyField(related_name='profile_favourites', to='companyPointer.Company')),
                ('interests', models.ManyToManyField(related_name='profile_interests', to='companyPointer.Tag')),
                ('related_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyPointer.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
